#!/bin/bash
clear
RETVAL=$(whiptail --title "Domoticz Menu" --menu "" 23 63 0 \
"1" "Backup Domoticz" \
"2" "Backup Dashticz" \
"3" "Backup Web Server" \
"4" "Configure raspiBackup" \
"5" "Start raspiBackup" \
"6" "Domoticz Status" \
"7" "Stop Domoticz and Disable Monitoring" \
"8" "Start Domoticz and Enable Monitoring" \
"9" "Restart Domoticz" \
"10" "Monitoring Status" \
"11" "Disable Monitoring All Services" \
"12" "Enable Monitoring All Services" \
"13" "Quit Monitoring" \
"14" "Start Monitoring" \
"15" "Updating and Upgrading Raspberry Pi OS" \
"16" "Shutdown System" \
"17" "Reboot System" \
3>&1 1>&2 2>&3)

# Below you can enter the corresponding commands
# Make menu script executable

case $RETVAL in
    1) sudo bash /home/pi/domoticz/scripts/shell/domoticz_backup.sh ;;
    2) sudo bash /home/pi/domoticz/scripts/shell/dashticz_backup.sh ;;
    3) sudo bash /home/pi/domoticz/scripts/shell/www_backup.sh ;;
    4) sudo raspiBackupInstallUI.sh ;;
    5) sudo raspiBackup.sh -m detailed ;;
    6) sudo service domoticz.sh status ;;
    7) sudo monit unmonitor domoticz && sudo service domoticz.sh stop && echo Domoticz Stopped and Monitoring Disabled ;;
    8) sudo service domoticz.sh start && sudo monit monitor domoticz && echo Domoticz Started and Monitoring Enabled ;;
    9) sudo service domoticz.sh restart ;;
    10) sudo monit status ;;
    11) sudo monit unmonitor all && echo Monitoring All Services Disabled ;;
    13) sudo monit monitor all && echo Monitoring All Services Enabled ;;
    13) sudo monit quit && echo Monitoring Quitted ;;
    14) sudo monit && echo Monitoring Started ;;
    15) sudo apt update && sudo apt -y upgrade ;;
    16) sudo shutdown -h now ;;
    17) sudo shutdown -r now ;;
    *) echo "You chose Cancel." ;;
esac
